FROM microsoft/dotnet:2.1.6-runtime-stretch-slim

ARG branch=master

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
        libunwind8 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir Draughts
ADD https://github.com/RichTeaMan/Draughts/archive/$branch.tar.gz draughts.tar.gz
RUN tar -xzf draughts.tar.gz --strip-components=1 -C Draughts
WORKDIR /Draughts
RUN ./cake.sh -target=build
ENTRYPOINT ./cake.sh -target=Web-UI -contestant-file=/ai/ai.json
