FROM mcr.microsoft.com/dotnet/aspnet:3.1

LABEL org.opencontainers.image.source https://github.com/RichTeaMan/Draughts

COPY Draughts.Web.UI/bin/Release/netcoreapp3.1/publish/ /Draughts/
WORKDIR /Draughts
ENTRYPOINT dotnet Draughts.Web.UI.dll -- /ai/ai.json
